### ISSUE TITLE
exp10it升级2.6.65后报ImportError: cannot import name 'homePath'

### ISSUE THREAD

**Issue by XTpeeps** [3xp10it/bypass_waf#12]
我最近一次可用的exp10it版本2.6.58
最近运行xwaf，升级了exp10it2.6.65.升级后已经不能导入exp10it中的 'homePath'。
![image](https://user-images.githubusercontent.com/9640837/33195278-2ac971ec-d111-11e7-8b6c-4e836d782abd.png)

exp10it模块貌似已经更新为get_home_path。尝试把第43行和18行的homepath替换成get_home_path。
但运行报错：

![image](https://user-images.githubusercontent.com/9640837/33195260-f980c05e-d110-11e7-811e-fc80ec7b4bcb.png)

**Comment by legendsec** [comment]
我也遇到同样的问题，如何解决呢？

**Comment by 3xp10it** [comment]
已更新,重新运行即可.

**Comment by legendsec** [comment]
运行还是有问题
![1](https://user-images.githubusercontent.com/13389492/33535638-ba874eaa-d8e9-11e7-8daf-dce0d8f59111.jpg)

**Comment by legendsec** [comment]
什么原因，望快回复。非常感谢。

**Comment by 3xp10it** [comment]
`rm -r ~/.3xp10it`再运行试试

**Comment by legendsec** [comment]
最近升级后又报错了，不知道什么原因呀。



在 2017-12-04 12:39:11，"3xp10it" <notifications@github.com> 写道：


rm -r ~/.3xp10it再运行试试

**Comment by 3xp10it** [comment]
报错详情是什么?


在 2018年1月16日 13:38:51, legendsec (notifications@github.com) 写到:

最近升级后又报错了，不知道什么原因呀。



在 2017-12-04 12:39:11，"3xp10it" <notifications@github.com> 写道：


rm -r ~/.3xp10it再运行试试

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/3xp10it/bypass_waf/issues/12#issuecomment-357858921>,
or mute the thread
